# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_spark_session": "00_spark_core.ipynb"}

modules = ["spark_core.py"]

doc_url = "https://HansjoergW.github.io/udemy_spark/"

git_url = "https://github.com/HansjoergW/udemy_spark/tree/master/"

def custom_doc_links(name): return None
