# AUTOGENERATED! DO NOT EDIT! File to edit: 00_spark_core.ipynb (unless otherwise specified).

__all__ = ['get_spark_session']

# Cell
import findspark
from pyspark.sql import SparkSession
def get_spark_session(appname = "default"):
    findspark.init()
    return SparkSession.builder.appName(appname).getOrCreate()